//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.Database
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;

    public partial class MedicalHistory
    {
        public int ID { get; set; }
        public int IDPatient { get; set; }
        public int IDEmployee { get; set; }
        public int IDDiagnose { get; set; }
        public string Treatment { get; set; }
        public System.DateTime DateOfTheDisease { get; set; }
        public System.DateTime DateOfCure { get; set; }
        public int IDTypeOfTreatment { get; set; }
    
        public virtual Diagnoses Diagnoses { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Patients Patients { get; set; }
        public virtual TypeOfTreatments TypeOfTreatments { get; set; }

        public string PatientFullName { get{ return Patients.Surname + " " + Patients.Name + " " + Patients.Patronymic;}}
        public string EmployeeFullName { get { return Employee.Surname + " " + Employee.Name + " " + Employee.Patronymic;}}
        public string DiagnoseTitle { get { return Diagnoses.NameDiagnose;}}
        public string TypeOfTreatmentTitle { get { return TypeOfTreatments.TypeOfTreatment; } }

        public string DateOfTheDiseaseFormat
        {
            get
            {
                // Устанавливаем русскую культуру
                CultureInfo russianCulture = new CultureInfo("ru-RU");

                // Форматируем дату в нужный формат
                string formattedDate = DateOfTheDisease.ToString("d MMMM yyyy", russianCulture);

                // Выводим отформатированную дату
                return formattedDate;

            }
        }
        public string DateOfCureFormat
        {
            get
            {
                // Устанавливаем русскую культуру
                CultureInfo russianCulture = new CultureInfo("ru-RU");

                // Форматируем дату в нужный формат
                string formattedDate = DateOfCure.ToString("d MMMM yyyy", russianCulture);

                // Выводим отформатированную дату
                return formattedDate;

            }
        }
    }

}
